// @summary Tailwind config with design tokens, fonts, and custom color/spacing scales
import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/client/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        bg: "rgb(var(--color-bg-rgb) / <alpha-value>)",
        "bg-base": "rgb(var(--color-bg-base-rgb) / <alpha-value>)",
        "bg-elevated": "rgb(var(--color-bg-elevated-rgb) / <alpha-value>)",
        "bg-sunken": "rgb(var(--color-bg-sunken-rgb) / <alpha-value>)",
        "bg-surface-info": "rgb(var(--color-bg-surface-info-rgb) / <alpha-value>)",
        "bg-surface-success": "rgb(var(--color-bg-surface-success-rgb) / <alpha-value>)",
        "bg-surface-warning": "rgb(var(--color-bg-surface-warning-rgb) / <alpha-value>)",
        "bg-surface-error": "rgb(var(--color-bg-surface-error-rgb) / <alpha-value>)",
        surface: "rgb(var(--color-surface-rgb) / <alpha-value>)",
        "surface-dark": "rgb(var(--color-bg-surface-dark-rgb) / <alpha-value>)",
        "surface-default": "rgb(var(--color-bg-surface-default-rgb) / <alpha-value>)",
        "surface-light": "rgb(var(--color-bg-surface-light-rgb) / <alpha-value>)",
        "fill-primary": "rgb(var(--color-bg-fill-primary-rgb) / <alpha-value>)",
        "fill-primary-hover": "rgb(var(--color-bg-fill-primary-hover-rgb) / <alpha-value>)",
        "fill-secondary": "rgb(var(--color-bg-fill-secondary-rgb) / <alpha-value>)",
        "fill-secondary-hover": "rgb(var(--color-bg-fill-secondary-hover-rgb) / <alpha-value>)",
        "fill-ghost-hover": "rgb(var(--color-bg-fill-ghost-hover-rgb) / <alpha-value>)",
        "fill-active": "rgb(var(--color-bg-fill-active-rgb) / <alpha-value>)",
        "fill-active-hover": "rgb(var(--color-bg-fill-active-hover-rgb) / <alpha-value>)",
        "fill-error": "rgb(var(--color-bg-fill-error-rgb) / <alpha-value>)",
        "fill-notification": "rgb(var(--color-bg-fill-notification-rgb) / <alpha-value>)",
        "fill-tertiary": "rgb(var(--color-fill-tertiary-rgb) / <alpha-value>)",
        "fill-tertiary-hover": "rgb(var(--color-fill-tertiary-hover-rgb) / <alpha-value>)",
        "fill-strong": "rgb(var(--color-fill-strong-rgb) / <alpha-value>)",
        "fill-dark": "rgb(var(--color-fill-dark-rgb) / <alpha-value>)",
        selection: "rgb(var(--color-selection-rgb) / <alpha-value>)",
        "surface-muted": "rgb(var(--color-surface-muted-rgb) / <alpha-value>)",
        "surface-strong": "rgb(var(--color-surface-strong-rgb) / <alpha-value>)",
        text: "rgb(var(--color-text-rgb) / <alpha-value>)",
        "text-default": "rgb(var(--color-text-default-rgb) / <alpha-value>)",
        "text-strong": "rgb(var(--color-text-strong-rgb) / <alpha-value>)",
        "text-secondary": "rgb(var(--color-text-secondary-rgb) / <alpha-value>)",
        "text-tertiary": "rgb(var(--color-text-tertiary-rgb) / <alpha-value>)",
        "text-info": "rgb(var(--color-text-info-rgb) / <alpha-value>)",
        "text-success": "rgb(var(--color-text-success-rgb) / <alpha-value>)",
        "text-warning": "rgb(var(--color-text-warning-rgb) / <alpha-value>)",
        "text-error": "rgb(var(--color-text-error-rgb) / <alpha-value>)",
        "text-script-gray": "rgb(var(--color-text-script-gray-rgb) / <alpha-value>)",
        "text-script-blue": "rgb(var(--color-text-script-blue-rgb) / <alpha-value>)",
        "text-script-green": "rgb(var(--color-text-script-green-rgb) / <alpha-value>)",
        "text-script-orange": "rgb(var(--color-text-script-orange-rgb) / <alpha-value>)",
        "text-script-red": "rgb(var(--color-text-script-red-rgb) / <alpha-value>)",
        "text-soft": "rgb(var(--color-text-soft-rgb) / <alpha-value>)",
        "text-muted": "rgb(var(--color-text-muted-rgb) / <alpha-value>)",
        "text-subtle": "rgb(var(--color-text-subtle-rgb) / <alpha-value>)",
        "text-inverse": "rgb(var(--color-text-inverse-rgb) / <alpha-value>)",
        "icon-default": "rgb(var(--color-icon-default-rgb) / <alpha-value>)",
        "icon-strong": "rgb(var(--color-icon-strong-rgb) / <alpha-value>)",
        "icon-secondary": "rgb(var(--color-icon-secondary-rgb) / <alpha-value>)",
        "icon-tertiary": "rgb(var(--color-icon-tertiary-rgb) / <alpha-value>)",
        "icon-info": "rgb(var(--color-icon-info-rgb) / <alpha-value>)",
        "icon-success": "rgb(var(--color-icon-success-rgb) / <alpha-value>)",
        "icon-warning": "rgb(var(--color-icon-warning-rgb) / <alpha-value>)",
        "icon-error": "rgb(var(--color-icon-error-rgb) / <alpha-value>)",
        muted: "rgb(var(--color-text-muted-rgb) / <alpha-value>)",
        accent: "rgb(var(--color-accent-rgb) / <alpha-value>)",
        "accent-hover": "rgb(var(--color-accent-hover-rgb) / <alpha-value>)",
        danger: "rgb(var(--color-danger-rgb) / <alpha-value>)",
        success: "rgb(var(--color-success-rgb) / <alpha-value>)",
        info: "rgb(var(--color-info-rgb) / <alpha-value>)",
        warning: "rgb(var(--color-warning-rgb) / <alpha-value>)",
        attention: "rgb(var(--color-attention-rgb) / <alpha-value>)",
        border: "rgb(var(--color-border-rgb) / <alpha-value>)",
        "border-default": "rgb(var(--color-border-default-rgb) / <alpha-value>)",
        "border-strong": "rgb(var(--color-border-strong-rgb) / <alpha-value>)",
        "border-super": "rgb(var(--color-border-super-rgb) / <alpha-value>)",
        "border-weak": "rgb(var(--color-border-weak-rgb) / <alpha-value>)",
        "border-focus": "rgb(var(--color-border-focus-rgb) / <alpha-value>)",
        "border-focus-danger": "rgb(var(--color-border-focus-danger-rgb) / <alpha-value>)",
        "border-hover": "rgb(var(--color-border-hover-rgb) / <alpha-value>)",
        "border-info": "rgb(var(--color-border-info-rgb) / <alpha-value>)",
        "border-success": "rgb(var(--color-border-success-rgb) / <alpha-value>)",
        "border-warning": "rgb(var(--color-border-warning-rgb) / <alpha-value>)",
        "border-error": "rgb(var(--color-border-error-rgb) / <alpha-value>)",
        overlay: "rgb(var(--color-overlay-rgb) / <alpha-value>)",
        "gizmo-x": "rgb(var(--color-gizmo-x-rgb) / <alpha-value>)",
        "gizmo-y": "rgb(var(--color-gizmo-y-rgb) / <alpha-value>)",
        "gizmo-z": "rgb(var(--color-gizmo-z-rgb) / <alpha-value>)",
        "provider-anthropic": "rgb(var(--color-provider-anthropic-rgb) / <alpha-value>)",
        "provider-openai": "rgb(var(--color-provider-openai-rgb) / <alpha-value>)",
        "provider-chatgpt": "rgb(var(--color-provider-chatgpt-rgb) / <alpha-value>)",
        "provider-gemini": "rgb(var(--color-provider-gemini-rgb) / <alpha-value>)",
        "provider-vertex": "rgb(var(--color-provider-vertex-rgb) / <alpha-value>)",
        "knowledge-pattern": "rgb(var(--color-knowledge-pattern-rgb) / <alpha-value>)",
        "knowledge-backlog": "rgb(var(--color-knowledge-backlog-rgb) / <alpha-value>)",
        "knowledge-discovery": "rgb(var(--color-knowledge-discovery-rgb) / <alpha-value>)",
        "knowledge-preference": "rgb(var(--color-knowledge-preference-rgb) / <alpha-value>)",
        "knowledge-correction": "rgb(var(--color-knowledge-correction-rgb) / <alpha-value>)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
      },
      spacing: {
        xs: "var(--space-xs)",
        sm: "var(--space-sm)",
        md: "var(--space-md)",
        lg: "var(--space-lg)",
        xl: "var(--space-xl)",
      },
      fontSize: {
        "2xs": "0.625rem",
        "xs-": "0.6875rem",
      },
      maxWidth: {
        message: "80%",
        assistant: "88%",
        "tool-row": "94%",
        app: "1200px",
      },
      boxShadow: {
        panel: "var(--shadow-panel)",
      },
      fontFamily: {
        sans: ["IBM Plex Sans", "ui-sans-serif", "system-ui"],
        mono: ["IBM Plex Mono", "ui-monospace", "SFMono-Regular"],
      },
    },
  },
};

export default config;
