#!/usr/bin/env bun
// Syncs bootstrap/skills/vfx-recipe/references/ from overdare/creator-guide-eng.
// Usage: bun run apps/overdare-ai-agent/scripts/sync-vfx-references.ts
import { mkdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";

const REPO = "overdare/creator-guide-eng";
const BASE = "official-asset-info";
const OUT_DIR = join(import.meta.dir, "../bootstrap/skills/vfx-recipe/references");

async function gh(args: string[]): Promise<string> {
  const proc = Bun.spawn(["gh", ...args], { stdout: "pipe", stderr: "pipe" });
  const [out, err, code] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ]);
  if (code !== 0) throw new Error(`gh ${args.join(" ")} failed: ${err.slice(0, 300)}`);
  return out;
}

const fetchRaw = (path: string) =>
  gh(["api", "-H", "Accept: application/vnd.github.raw", `repos/${REPO}/contents/${BASE}/${path}`]);

function stamp(sha: string): string {
  return `<!-- Generated by scripts/sync-vfx-references.ts from ${REPO}@${sha} — do not edit by hand -->\n\n`;
}

/** Strips HTML tags, decodes common entities, collapses whitespace. <br> becomes " / ". */
function stripHtml(cell: string): string {
  return cell
    .replace(/<br\s*\/?>/g, " / ")
    .replace(/<[^>]+>/g, "")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * vfxpreset-asset-list.md is one serialized HTML <table>. Cell indexes (0-based):
 * 2=row number, 4=category(primary), 5=category(secondary), 6=genre, 7=resource name,
 * 9=long Korean description ending in an English "키워드: a, b, c" line, 10=Studio display name.
 * Output keeps only English fields (repo is English-only): name, display name,
 * categories, genre, and the extracted keyword list.
 */
function transformPresets(src: string, sha: string): string {
  const rows = [...src.matchAll(/<tr>([\s\S]*?)<\/tr>/g)].map((m) =>
    [...m[1].matchAll(/<td>([\s\S]*?)<\/td>/g)].map((c) => c[1]),
  );
  const lines: string[] = [];
  for (const cells of rows) {
    if (cells.length < 11) continue;
    const name = stripHtml(cells[7]);
    if (!name.startsWith("VFX_")) continue;
    const keywords =
      stripHtml(cells[9])
        .match(/키워드:\s*([A-Za-z0-9_,\- ]+)/)?.[1]
        ?.trim() ?? "";
    const display = stripHtml(cells[10]);
    const esc = (s: string) => s.replace(/\|/g, "\\|");
    lines.push(
      `| ${esc(name)} | ${esc(display)} | ${esc(stripHtml(cells[4]))} | ${esc(stripHtml(cells[5]))} | ${esc(stripHtml(cells[6]))} | ${esc(keywords)} |`,
    );
  }
  return (
    stamp(sha) +
    "# VFXPreset Catalog\n\n" +
    "One row per official preset. Grep this file case-insensitively by English keywords, " +
    "category, or display name; the Resource column feeds `VFXPreset.PresetName` directly.\n\n" +
    "| Resource | DisplayName | Category | Subcategory | Genre | Keywords |\n" +
    "|---|---|---|---|---|---|\n" +
    `${lines.join("\n")}\n`
  );
}

/** sources doc is already agent-friendly: drop thumbnails and maintainer HTML comments only. */
function transformSources(src: string, sha: string): string {
  const cleaned = src
    .replace(/<!--[\s\S]*?-->/g, "")
    .split("\n")
    .filter((line) => !/^\s*<img\s/.test(line))
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
  return `${stamp(sha) + cleaned}\n`;
}

/** Pulls a scalar or flow-list ("[a, b]") value out of the template frontmatter. */
function fmField(frontmatter: string, key: string): string {
  const m = frontmatter.match(new RegExp(`^${key}:\\s*(.+)$`, "m"));
  if (!m) return "";
  return m[1]
    .replace(/^\[|\]$/g, "")
    .replace(/"/g, "")
    .trim();
}

function indexLine(fileName: string, content: string): string {
  const fm = content.match(/^---\n([\s\S]*?)\n---/)?.[1] ?? "";
  const parts = [
    `category: ${fmField(fm, "category")}`,
    `elements: ${fmField(fm, "elements")}`,
    `sources: ${fmField(fm, "sources")}`,
    `patterns: ${fmField(fm, "patterns")}`,
    `keywords: ${fmField(fm, "keywords_en")}`,
  ];
  return `- **${fileName}** — ${fmField(fm, "title")} · ${parts.join(" · ")}`;
}

async function main() {
  const sha = (await gh(["api", `repos/${REPO}/commits/HEAD`, "--jq", ".sha"])).trim().slice(0, 12);

  const templateNames: string[] = JSON.parse(
    await gh(["api", `repos/${REPO}/contents/${BASE}/vfx-recipe-template`, "--jq", "[.[].name]"]),
  ).sort();

  const [presetsSrc, sourcesSrc, ...templates] = await Promise.all([
    fetchRaw("vfxpreset-asset-list.md"),
    fetchRaw("vfxsource-asset-list.md"),
    ...templateNames.map((n) => fetchRaw(`vfx-recipe-template/${n}`)),
  ]);

  const presetsOut = transformPresets(presetsSrc, sha);
  const presetCount = presetsOut.split("\n").filter((l) => l.startsWith("| VFX_")).length;
  if (presetCount < 100) throw new Error(`suspiciously few presets (${presetCount}) — upstream format changed?`);

  await rm(OUT_DIR, { recursive: true, force: true });
  await mkdir(join(OUT_DIR, "templates"), { recursive: true });

  await writeFile(join(OUT_DIR, "presets.md"), presetsOut);
  await writeFile(join(OUT_DIR, "sources.md"), transformSources(sourcesSrc, sha));
  for (let i = 0; i < templateNames.length; i++) {
    await writeFile(join(OUT_DIR, "templates", templateNames[i]), stamp(sha) + templates[i]);
  }
  const index =
    stamp(sha) +
    "# VFX Recipe Template Index\n\n" +
    "Read this file first, pick candidates, then read only the chosen template file.\n\n" +
    `${templateNames.map((n, i) => indexLine(n, templates[i])).join("\n")}\n`;
  await writeFile(join(OUT_DIR, "templates", "00_INDEX.md"), index);

  console.log(`synced @${sha}: ${presetCount} presets, ${templateNames.length} templates`);
}

await main();
