// @summary Tests provider selection and the shared generate-and-store image tool contract.

import { describe, expect, test } from "bun:test";
import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { isAbsolute, join, relative } from "node:path";
import type { Tool } from "@diligent/core/tool-contract";
import { resolvePaths } from "@diligent/runtime";
import {
  createImageGenerationToolProvider,
  type GeminiImageConfig,
  type GenerateCodexImage,
  type GenerateGeminiImage,
} from "../../../src/tools/image-generation";

function project(): { cwd: string; cleanup(): void } {
  const cwd = join(tmpdir(), `image-generation-${process.pid}-${Date.now()}-${Math.random()}`);
  mkdirSync(cwd, { recursive: true });
  return { cwd, cleanup: () => rmSync(cwd, { recursive: true, force: true }) };
}

async function toolFor(input: {
  cwd: string;
  generateCodexImage: GenerateCodexImage;
  generateGeminiImage: GenerateGeminiImage;
  resolveGeminiImageConfig: () => Promise<GeminiImageConfig | undefined>;
  approve?: "once" | "reject";
}): Promise<Tool | undefined> {
  const provider = createImageGenerationToolProvider({
    generateCodexImage: input.generateCodexImage,
    generateGeminiImage: input.generateGeminiImage,
    resolveGeminiImageConfig: input.resolveGeminiImageConfig,
  });
  const tools = await provider.createTools({
    cwd: input.cwd,
    host: { approve: async () => input.approve ?? "once" },
  });
  return tools.find((candidate) => candidate.name === "generate_image");
}

describe("generate_image", () => {
  test.each(["codex", "gemini"] as const)("does not save a %s result after cancellation", async (provider) => {
    const { cwd, cleanup } = project();
    const controller = new AbortController();
    try {
      const tool = await toolFor({
        cwd,
        resolveGeminiImageConfig: async () => ({ apiKey: "test-key", model: "test-model" }),
        generateGeminiImage: async () => {
          controller.abort(new Error("cancelled before saving"));
          return { bytes: Buffer.from("image"), mediaType: "image/png", model: "test-model" };
        },
        generateCodexImage: async () => {
          controller.abort(new Error("cancelled before saving"));
          return { sourcePath: join(cwd, "unused.png") };
        },
      });
      await expect(
        tool!.execute(
          { prompt: "A blue coin", provider },
          { toolCallId: "test", signal: controller.signal, abort: () => {} },
        ),
      ).rejects.toThrow("cancelled before saving");
      expect(existsSync(join(resolvePaths(cwd).images, "generated"))).toBe(false);
    } finally {
      cleanup();
    }
  });

  test("does not start generation if cancelled while resolving credentials", async () => {
    const { cwd, cleanup } = project();
    const controller = new AbortController();
    let generated = false;
    try {
      const generate = async (): Promise<never> => {
        generated = true;
        throw new Error("must not start");
      };
      const tool = await toolFor({
        cwd,
        resolveGeminiImageConfig: async () => {
          controller.abort(new Error("cancelled during configuration"));
          return undefined;
        },
        generateCodexImage: generate,
        generateGeminiImage: generate,
      });
      await expect(
        tool!.execute({ prompt: "A blue coin" }, { toolCallId: "test", signal: controller.signal, abort: () => {} }),
      ).rejects.toThrow("cancelled during configuration");
      expect(generated).toBe(false);
    } finally {
      cleanup();
    }
  });

  test("uses the configured Gemini API key by default and stores its generated bytes", async () => {
    const { cwd, cleanup } = project();
    const geminiCalls: Array<{ apiKey: string; prompt: string; model: string }> = [];
    let codexCalls = 0;

    try {
      const tool = await toolFor({
        cwd,
        resolveGeminiImageConfig: async () => ({ apiKey: "gemini-key", model: "gemini-image-model" }),
        generateGeminiImage: async ({ apiKey, prompt, model }) => {
          geminiCalls.push({ apiKey, prompt, model });
          return { bytes: Buffer.from("gemini-image"), mediaType: "image/png", model };
        },
        generateCodexImage: async () => {
          codexCalls += 1;
          throw new Error("Codex must not run");
        },
      });
      const result = await tool!.execute(
        { prompt: "A square blue coin icon" },
        { toolCallId: "test", signal: new AbortController().signal, abort: () => {} },
      );
      const output = JSON.parse(result.output) as {
        file: string;
        provider: string;
        source: string;
        model?: string;
      };

      expect(geminiCalls).toEqual([
        { apiKey: "gemini-key", prompt: "A square blue coin icon", model: "gemini-image-model" },
      ]);
      expect(codexCalls).toBe(0);
      expect(output).toMatchObject({ provider: "gemini", source: "gemini-api", model: "gemini-image-model" });
      expect(output.file.startsWith(join(resolvePaths(cwd).images, "generated"))).toBe(true);
      expect(await readFile(output.file, "utf8")).toBe("gemini-image");
      expect(result.outputImages?.[0]?.source.media_type).toBe("image/png");
    } finally {
      cleanup();
    }
  });

  test("falls back to managed Codex OAuth when no Gemini API key is configured", async () => {
    const { cwd, cleanup } = project();
    const sourcePath = join(cwd, "codex-output.webp");
    writeFileSync(sourcePath, "codex-image");
    let geminiCalls = 0;

    try {
      const tool = await toolFor({
        cwd,
        resolveGeminiImageConfig: async () => undefined,
        generateGeminiImage: async () => {
          geminiCalls += 1;
          throw new Error("Gemini must not run");
        },
        generateCodexImage: async ({ prompt }) => ({ sourcePath, revisedPrompt: `${prompt} refined` }),
      });
      const result = await tool!.execute(
        { prompt: "A red button" },
        { toolCallId: "test", signal: new AbortController().signal, abort: () => {} },
      );
      const output = JSON.parse(result.output) as {
        file: string;
        provider: string;
        source: string;
        revisedPrompt?: string;
      };

      expect(geminiCalls).toBe(0);
      expect(output).toMatchObject({
        provider: "codex",
        source: "codex-oauth",
        revisedPrompt: "A red button refined",
      });
      expect(await readFile(output.file, "utf8")).toBe("codex-image");
      expect(result.outputImages?.[0]?.source.media_type).toBe("image/webp");
    } finally {
      cleanup();
    }
  });

  test("honors an explicit Codex selection without reading Gemini credentials", async () => {
    const { cwd, cleanup } = project();
    const sourcePath = join(cwd, "codex-output.png");
    writeFileSync(sourcePath, "codex-image");
    let credentialReads = 0;

    try {
      const tool = await toolFor({
        cwd,
        resolveGeminiImageConfig: async () => {
          credentialReads += 1;
          return { apiKey: "gemini-key", model: "gemini-image-model" };
        },
        generateGeminiImage: async () => {
          throw new Error("Gemini must not run");
        },
        generateCodexImage: async () => ({ sourcePath }),
      });
      const result = await tool!.execute(
        { prompt: "A red button", provider: "codex" },
        { toolCallId: "test", signal: new AbortController().signal, abort: () => {} },
      );

      expect(credentialReads).toBe(0);
      expect(JSON.parse(result.output)).toMatchObject({ provider: "codex" });
    } finally {
      cleanup();
    }
  });

  test("reports a missing key for an explicit Gemini selection", async () => {
    const { cwd, cleanup } = project();

    try {
      const tool = await toolFor({
        cwd,
        resolveGeminiImageConfig: async () => undefined,
        generateGeminiImage: async () => {
          throw new Error("Gemini must not run");
        },
        generateCodexImage: async () => {
          throw new Error("Codex must not run");
        },
      });

      await expect(
        tool!.execute(
          { prompt: "A red button", provider: "gemini" },
          { toolCallId: "test", signal: new AbortController().signal, abort: () => {} },
        ),
      ).rejects.toThrow("Gemini API key is not configured");
    } finally {
      cleanup();
    }
  });

  test("does not silently spend Codex quota after a configured Gemini request fails", async () => {
    const { cwd, cleanup } = project();
    let codexCalls = 0;

    try {
      const tool = await toolFor({
        cwd,
        resolveGeminiImageConfig: async () => ({ apiKey: "gemini-key", model: "gemini-image-model" }),
        generateGeminiImage: async () => {
          throw new Error("Gemini quota exhausted");
        },
        generateCodexImage: async () => {
          codexCalls += 1;
          throw new Error("Codex must not run");
        },
      });

      await expect(
        tool!.execute(
          { prompt: "A red button" },
          { toolCallId: "test", signal: new AbortController().signal, abort: () => {} },
        ),
      ).rejects.toThrow("Gemini quota exhausted");
      expect(codexCalls).toBe(0);
    } finally {
      cleanup();
    }
  });

  test("does not read credentials or generate when approval is rejected", async () => {
    const { cwd, cleanup } = project();
    let calls = 0;

    try {
      const tool = await toolFor({
        cwd,
        approve: "reject",
        resolveGeminiImageConfig: async () => {
          calls += 1;
          return undefined;
        },
        generateGeminiImage: async () => {
          calls += 1;
          throw new Error("unused");
        },
        generateCodexImage: async () => {
          calls += 1;
          throw new Error("unused");
        },
      });
      await expect(
        tool!.execute(
          { prompt: "A red button" },
          { toolCallId: "test", signal: new AbortController().signal, abort: () => {} },
        ),
      ).resolves.toEqual({
        output: "[Rejected by user]",
        metadata: { error: true, operation: "image_generation" },
      });
      expect(calls).toBe(0);
    } finally {
      cleanup();
    }
  });

  test("returns an absolute stored path when the provider receives a relative cwd", async () => {
    const { cwd, cleanup } = project();

    try {
      const tool = await toolFor({
        cwd: relative(process.cwd(), cwd),
        resolveGeminiImageConfig: async () => ({ apiKey: "gemini-key", model: "gemini-image-model" }),
        generateGeminiImage: async ({ model }) => ({
          bytes: Buffer.from("image-data"),
          mediaType: "image/png",
          model,
        }),
        generateCodexImage: async () => {
          throw new Error("Codex must not run");
        },
      });
      const result = await tool!.execute(
        { prompt: "A red button" },
        { toolCallId: "test", signal: new AbortController().signal, abort: () => {} },
      );
      const output = JSON.parse(result.output) as { file: string };

      expect(isAbsolute(output.file)).toBe(true);
    } finally {
      cleanup();
    }
  });
});
