// @summary Manages .diligent directory structure with paths and gitignore setup
import { mkdir } from "node:fs/promises";
import { join } from "node:path";
import { homedir } from "node:os";
import { rename, stat } from "node:fs/promises";

export const DEFAULT_STORAGE_NAMESPACE = "diligent";

export function resolveStorageNamespace(env: NodeJS.ProcessEnv = process.env): string {
  const value = env.DILIGENT_STORAGE_NAMESPACE?.trim().toLowerCase();
  if (!value) return DEFAULT_STORAGE_NAMESPACE;
  if (!/^[a-z0-9-]+$/.test(value)) {
    throw new Error(`Invalid DILIGENT_STORAGE_NAMESPACE: ${value}`);
  }
  return value;
}

export function resolveProjectDirName(env: NodeJS.ProcessEnv = process.env): string {
  return `.${resolveStorageNamespace(env)}`;
}

/** Outcome of a namespace migration attempt. */
export type MigrationOutcome = "migrated" | "skipped_no_legacy" | "skipped_target_exists";

async function dirExists(path: string): Promise<boolean> {
  try {
    return (await stat(path)).isDirectory();
  } catch {
    return false;
  }
}

/**
 * Migrate the project-local storage directory from the legacy `.diligent/` namespace to the
 * currently configured namespace, if the namespace differs and the legacy directory exists.
 *
 * Matches the logic of `migrate_local_namespace_if_needed()` in `apps/overdare-ai-agent/src/storage.rs`
 * so that the TypeScript runtime can independently handle legacy directories when launched
 * without the Rust wrapper (e.g. direct CLI invocation, web-only deployment).
 */
export async function migrateNamespaceIfNeeded(
  projectRoot: string,
  env: NodeJS.ProcessEnv = process.env,
): Promise<MigrationOutcome> {
  const namespace = resolveStorageNamespace(env);
  if (namespace === DEFAULT_STORAGE_NAMESPACE) {
    return "skipped_no_legacy";
  }

  const legacyDir = join(projectRoot, `.${DEFAULT_STORAGE_NAMESPACE}`);
  const targetDir = join(projectRoot, `.${namespace}`);

  if (!(await dirExists(legacyDir))) return "skipped_no_legacy";
  if (await dirExists(targetDir)) return "skipped_target_exists";

  await rename(legacyDir, targetDir);
  return "migrated";
}

/**
 * Migrate the global (home-directory) storage directory from the legacy `~/.diligent/` namespace
 * to the currently configured namespace, if the namespace differs and the legacy directory exists.
 *
 * Matches the logic of `migrate_global_namespace_if_needed()` in `apps/overdare-ai-agent/src/storage.rs`.
 */
export async function migrateGlobalNamespaceIfNeeded(
  env: NodeJS.ProcessEnv = process.env,
): Promise<MigrationOutcome> {
  const namespace = resolveStorageNamespace(env);
  if (namespace === DEFAULT_STORAGE_NAMESPACE) {
    return "skipped_no_legacy";
  }

  const home = env.HOME ?? env.USERPROFILE ?? homedir();
  const legacyDir = join(home, `.${DEFAULT_STORAGE_NAMESPACE}`);
  const targetDir = join(home, `.${namespace}`);

  if (!(await dirExists(legacyDir))) return "skipped_no_legacy";
  if (await dirExists(targetDir)) return "skipped_target_exists";

  await rename(legacyDir, targetDir);
  return "migrated";
}

export interface DiligentPaths {
  root: string;
  sessions: string;
  knowledge: string;
  skills: string;
  images: string;
}

export function resolvePaths(projectRoot: string, env: NodeJS.ProcessEnv = process.env): DiligentPaths {
  const root = join(projectRoot, resolveProjectDirName(env));
  return {
    root,
    sessions: join(root, "sessions"),
    knowledge: join(root, "knowledge"),
    skills: join(root, "skills"),
    images: join(root, "images"),
  };
}

const GITIGNORE_CONTENT = `# Auto-generated by diligent
# Sessions and knowledge are machine-local, not version-controlled
sessions/
knowledge/
images/
logs/
`;

export async function ensureDiligentDir(
  projectRoot: string,
  env: NodeJS.ProcessEnv = process.env,
): Promise<DiligentPaths> {
  const paths = resolvePaths(projectRoot, env);
  await mkdir(paths.sessions, { recursive: true });
  await mkdir(paths.knowledge, { recursive: true });
  await mkdir(paths.skills, { recursive: true });
  await mkdir(paths.images, { recursive: true });

  const gitignorePath = join(paths.root, ".gitignore");
  const file = Bun.file(gitignorePath);
  if (!(await file.exists())) {
    await Bun.write(gitignorePath, GITIGNORE_CONTENT);
  }

  return paths;
}
