// @summary Manages .diligent directory structure with paths and gitignore setup
import { mkdir } from "node:fs/promises";
import { join } from "node:path";

const DILIGENT_DIR = ".diligent";

export interface DiligentPaths {
  root: string;
  sessions: string;
  knowledge: string;
  skills: string;
  images: string;
}

export function resolvePaths(projectRoot: string): DiligentPaths {
  const root = join(projectRoot, DILIGENT_DIR);
  return {
    root,
    sessions: join(root, "sessions"),
    knowledge: join(root, "knowledge"),
    skills: join(root, "skills"),
    images: join(root, "images"),
  };
}

const GITIGNORE_CONTENT = `# Auto-generated by diligent
# Sessions and knowledge are machine-local, not version-controlled
sessions/
knowledge/
images/
`;

/**
 * Ensure .diligent/ directory structure exists.
 * Creates dirs and .gitignore if missing. Idempotent.
 */
export async function ensureDiligentDir(projectRoot: string): Promise<DiligentPaths> {
  const paths = resolvePaths(projectRoot);
  await mkdir(paths.sessions, { recursive: true });
  await mkdir(paths.knowledge, { recursive: true });
  await mkdir(paths.skills, { recursive: true });
  await mkdir(paths.images, { recursive: true });

  const gitignorePath = join(paths.root, ".gitignore");
  const file = Bun.file(gitignorePath);
  if (!(await file.exists())) {
    await Bun.write(gitignorePath, GITIGNORE_CONTENT);
  }

  return paths;
}
