// @summary Manages .diligent directory structure with paths and gitignore setup
import { mkdir } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";

export const DEFAULT_STORAGE_NAMESPACE = "diligent";

export function resolveStorageNamespace(env: NodeJS.ProcessEnv = process.env): string {
  const value = env.DILIGENT_STORAGE_NAMESPACE?.trim().toLowerCase();
  if (!value) return DEFAULT_STORAGE_NAMESPACE;
  if (!/^[a-z0-9-]+$/.test(value)) {
    throw new Error(`Invalid DILIGENT_STORAGE_NAMESPACE: ${value}`);
  }
  return value;
}

export function resolveProjectDirName(env: NodeJS.ProcessEnv = process.env): string {
  return `.${resolveStorageNamespace(env)}`;
}

export interface DiligentPaths {
  root: string;
  sessions: string;
  knowledge: string;
  skills: string;
  images: string;
}

export function resolvePaths(projectRoot: string, env: NodeJS.ProcessEnv = process.env): DiligentPaths {
  const root = join(projectRoot, resolveProjectDirName(env));
  return {
    root,
    sessions: join(root, "sessions"),
    knowledge: join(root, "knowledge"),
    skills: join(root, "skills"),
    images: join(root, "images"),
  };
}

const GITIGNORE_CONTENT = `# Auto-generated by diligent
# Sessions and knowledge are machine-local, not version-controlled
sessions/
knowledge/
images/
logs/
`;

export async function ensureDiligentDir(
  projectRoot: string,
  env: NodeJS.ProcessEnv = process.env,
): Promise<DiligentPaths> {
  if (resolveStorageNamespace(env) !== DEFAULT_STORAGE_NAMESPACE) {
    await migrateLocalNamespaceIfNeeded(projectRoot, env);
  }

  const paths = resolvePaths(projectRoot, env);
  await mkdir(paths.sessions, { recursive: true });
  await mkdir(paths.knowledge, { recursive: true });
  await mkdir(paths.skills, { recursive: true });
  await mkdir(paths.images, { recursive: true });

  const gitignorePath = join(paths.root, ".gitignore");
  const file = Bun.file(gitignorePath);
  if (!(await file.exists())) {
    await Bun.write(gitignorePath, GITIGNORE_CONTENT);
  }

  return paths;
}

// ---------------------------------------------------------------------------
// Namespace migration — mirrors the Rust launcher's storage.rs logic
// ---------------------------------------------------------------------------

export type MigrationOutcome =
  | { kind: "migrated"; from: string; to: string }
  | { kind: "skipped_no_legacy" }
  | { kind: "skipped_target_exists" };

/**
 * Core migration primitive: renames `legacy` to `target` if:
 * - `target` does not already exist (would silently split history if we skipped this)
 * - `legacy` exists
 *
 * Mirrors `migrate_namespace_if_needed()` in `apps/overdare-ai-agent/src/storage.rs`.
 */
export async function migrateNamespaceIfNeeded(legacy: string, target: string): Promise<MigrationOutcome> {
  const { rename, access: fsAccess } = await import("node:fs/promises");

  const exists = async (path: string) => {
    try {
      await fsAccess(path);
      return true;
    } catch {
      return false;
    }
  };

  if (await exists(target)) return { kind: "skipped_target_exists" };
  if (!(await exists(legacy))) return { kind: "skipped_no_legacy" };

  await rename(legacy, target);
  return { kind: "migrated", from: legacy, to: target };
}

/**
 * Migrate the project-local storage directory from `.diligent/` to `.{namespace}/`.
 * No-op when the current namespace is already "diligent".
 */
export async function migrateLocalNamespaceIfNeeded(
  cwd: string,
  env: NodeJS.ProcessEnv = process.env,
): Promise<MigrationOutcome> {
  const namespace = resolveStorageNamespace(env);
  if (namespace === DEFAULT_STORAGE_NAMESPACE) return { kind: "skipped_no_legacy" };

  const legacy = join(cwd, `.${DEFAULT_STORAGE_NAMESPACE}`);
  const target = join(cwd, `.${namespace}`);
  return migrateNamespaceIfNeeded(legacy, target);
}

/**
 * Migrate the global (home-directory) storage from `~/.diligent/` to `~/.{namespace}/`.
 * No-op when the current namespace is already "diligent".
 */
export async function migrateGlobalNamespaceIfNeeded(
  env: NodeJS.ProcessEnv = process.env,
): Promise<MigrationOutcome> {
  const namespace = resolveStorageNamespace(env);
  if (namespace === DEFAULT_STORAGE_NAMESPACE) return { kind: "skipped_no_legacy" };

  const home = homedir();
  const legacy = join(home, `.${DEFAULT_STORAGE_NAMESPACE}`);
  const target = join(home, `.${namespace}`);
  return migrateNamespaceIfNeeded(legacy, target);
}
